=== Terminal Copilot & Containerization

. Getting Started with Containerization

.Copilot Chat Prompt
[source,text]
@terminal I am new to containerization. Please explain the basics of containerization to me. What tools can I use? Which tool do you recommend?

[start=2]
. Getting Started with Docker

.Copilot Chat Prompt
[source,text]
@terminal How do I get started with Docker? Is there such a thing as a "Hello, World!" with Docker technology?

[start=3]
. Create a Docker Image for a Spring Boot Application

.Copilot Chat Prompt
[source,text]
@terminal I am a Java Spring Boot programmer. My manager told me I needed to deploy my latest Spring Boot application to the cloud using a Docker image. Can you explain how to create a Docker image for a standard Spring Boot application?

[start=4]
. Use Docker to Build the Application and Create the Deploy Image

.Copilot Chat Prompt
[source,text]
@terminal This is great! Thank you! One more thing: my manager said I need to use Docker to build and deploy the application. He mentioned something about a multi-stage Dockerfile containing a build container or image that builds the JAR file and then copies the built JAR file to the image used for deployment. Can you help me with this?

[start=5]
. Deploy the Docker Image to a Container Registry within AWS

.Copilot Chat Prompt
[source,text]
@terminal Finally, how do I push my final image to a container registry on AWS?

[start=6]
. Access the Containers running on Kubernetes.

.Copilot Chat Prompt
[source,text]
@terminal The ops team told me my image was used to deploy containers within a Kubernetes cluster. What is Kubernetes? Also, they said I can view my running application with some kind of command line tool. What is the command line tool used to administer Kubernetes? How do I access the cluster with it? Kubernetes is running on AWS.

[start=7]
. What are Kubernetes Pods?

.Copilot Chat Prompt
[source,text]
@terminal Explain to me what Kubernetes pods are. How do I view their health?

[start=8]
. Deploy my Spring Boot App to Kubernetes

.Copilot Chat Prompt
[source,text]
@terminal The ops team told me they have set up a Kubernetes cluster for testing and development. I must deploy my Spring Boot Application from the Container Registry to this new cluster. Also, my application needs a connection string environment variable to connect to the data when running in the cluster. How do I securely store the connection string in AWS and make it an environment variable on my running pods?

[start=9]
. Kubectl to Perform Deployment

.Copilot Chat Prompt
[source,text]
@terminal Thanks! This looks great. One last thing: how do I deploy this with kubectl?
