=== C++: Detect a Dangling Pointer

To run the following code, please create a "Hello World" style C++ project
using Visual Studio or JetBrain's CLion. You may use whatever project and
build tools you would like.

. Open the C++ file with the `main` function. Replace the code in the file,
   with this code.

[%linenums,cpp]
----
#include <iostream>

int main() {
    int *ptr = new int(10);

    std::cout << "Value before delete: " << *ptr << std::endl;

    delete ptr;

    std::cout << "Value after delete: " << *ptr << std::endl; 

    return 0;
}
----

Compile the code, and run it. The application will execute but the results will be strange.

[start=2]
. Can you identify the dangling pointer? If you run the code through a 
static code analysis tool it will tell you the dangling pointer occurs when 
the `ptr` variable is used after the memory has been freed with the `delete` 
operation.

[start=3]
. Highlight the code, right-click, and ask Copilot to fix the code. Apply 
   the recommended fix and ensure the code works as expected.

[start=4]
. Here is a reference solution to compare your code to.

[%linenums,cpp]
----
#include <iostream>

int main() {
  int *ptr = new int(10);

  std::cout << "Value before delete: " << *ptr << std::endl;
  delete ptr;

  return 0;
}
----
