=== Workspace New Command for a Python Project

The following prompts demonstrate how to create a new project with GitHub Copilot and its `@workspace /new` command. There are several iterations of the same prompt adding additional detail to the new project request to explore how far GitHub Copilot can go to create a great start to a new project!

To run these commands, open the GitHub Copilot in Visual Studio Code.

- Iteration 1 - Simply Create a Python Project

[source,text]
@workspace /new Create a new Python project.

- Iteration 2 - Create a simple Python Project

[source,text]
@workspace /new Create a new Python project do not include unit tests, requirements.txt, or a virtual environment configuration.

- Iteration 3 - Create a simple Python Project including Logging

[source,text]
@workspace /new Create a new Python project do not include unit tests, requirements.txt, or a virtual environment configuration. The project should include the Python standard library logger.

- Iteration 4 - Create a simple Python Project including Logging and Unit Tests

[source,text]
@workspace /new Create a new Python project do not include requirements.txt and a virtual environment configuration. The project should include the Python standard library logger. Also, include unit tests using using the unittest standard library module.

- Iteration 5 - Create a simple Python Project including Logging, Unit Tests, and Argument Parsing

[source,text]
@workspace /new Create a new Python project do not include requirements.txt and a virtual environment configuration. The project should include the Python standard library logger. Include unit tests using using the unittest standard library module. Include argument parsing using the argparse standard library module. The program should support an argument for verbose logging and loading a configuration file using the INI format.
