===  Demo: C++ Console App in VS Code

This is a demo to show how to use GitHub Copilot to help you write a new C++ program. These are suggested prompts to use with GitHub Copilot. Feel free modify them or add additional prompts to get the desired results.

. Create a "Hello, World!" Program

```text
Hello, I am new to C++ programming, but I do have computer programming experience. I would like to create a simple "Hello, World!" program in C++. Can you help me?
```

[start=2]
. Learn about Build Tools for C++ Project

[source,text]
Does C++ support any build configuration tools? If so, what are they and how do I use them? Which one do you recommend?

[start=3]
. Configure the C++ Project to Use CMake

[source,text]
Please explain how to configure a C++ project to use CMake. I would like an example of the CMakelists.txt file and how to build and run the project with CMake.

[start=4]
. Add Unit Testing to the C++ Project.

[source,text]
A friend of mine told me that I should add unit testing to my C++ project. Can you help me with that? Which C++ unit testing framework would you recommend?

[start=5]
. Add Google Test to the C++ Project.

[source,text]
Show me how to incorporate Google Test into the CMake build of my C++ project. Also, show me how to write a simple test case using Google Test.

[start=6]
. Setup Source Control for the C++ Project.

[source,text]
I need to work on my project on multiple computers and track changes to my code. Is there a programming tool that I could use for this? If so, which one do you recommend?

[start=7]
. Setup Git for the C++ Project.

[source,text]
Explain to me how to setup Git for my C++ project. I would like to know how to create a new repository, add files to the repository, and commit changes to the repository. Also, how do I exclude all of the files generate by CMake?