=== Workspace Scoped Prompts for a C++ Project

When chatting with GitHub Copilot it is possible to chat about your project and get specific answers. The key is context. When chatting with Copilot using no command in the prompt, the chat will be about the open files in your editor. If you wish to include all files in your project, the `@workspace` command must be prepended to the prompt.

==== Generating a C++ Project

The following iteration of prompts further refines the project creation instructions until the instructions match what we are looking for. Prompting is kind of like programming, but with human language.

- Iteration 1: Create a new C++ Project with a CMake Configuration

[source,text]
@workspace create a new cpp project with a cmake configuration

- Iteration 2: Create a new C++ Project with a CMake Configuration including Google Test

[source,text]
@workspace create a new cpp project with a cmake configuration, include support for unit tests with Google Test

- Iteration 3: Create a new C++ Project with Specific Specifications

[source,text]
@workspace Create a new cpp project with a cmake configuration and include support for unit tests with Google Test. The CMake version will be 3.28. The C++ version will be 23. The Google Test tag will be v14. Please include instructions on how to build the project with cmake instead of make. Also, please generate the appropriate .gitignore file, be sure to include .DS_Store for support on macOS.

==== Add a Person Class

The following iteration of prompts further refines the adding of a `Person` class instructions until the instructions match what we are looking for. This prompt usually requires working CMake configuration and `build` folder.

- Iteration 1: Create a new Person Class

[source,text]
@workspace add a person class file

- Iteration 2: Create a new Person Class with specific Fields

[source,text]
@workspace Add a person class in a new file, the person will have the following fields: first name, last name, age, street address, city, state, and zip code.

- Iteration 3: Create a new Person Class with specific Fields and Methods

[source,text]
@workspace Add a person class in a new file, the person will have the following fields: first name, last name, age, street address, city, state, and zip code. Make each field private with public get and set functions. Add a method that returns the full name of the person.

- Iteration 4: Create a new Person Class with Unit Tests

[source,text]
@workspace Add a person class in a new file, the person will have the following fields: first name, last name, age, street address, city, state, and zip code. Make each field private with public get and set functions. Add a method that returns the full name of the person. Please generate unit tests for all methods.

- Iteration 5: Create a new Person Class with Unit Tests and Add to CMake

[source,text]
@workspace Add a person class. Implement the class using a header file and a cpp file. The person will have the following fields: first name, last name, age, street address, city, state, and zip code. Make each field private with public get and set functions. Add a method that returns the full name of the person. Please generate unit tests for all methods. Please show me how to add the new class and unit tests to my CMake configuration.

==== Extract a New Address Class From Person Class

In this example, we will not iterate on each prompt; instead we will use a series a prompts to complete a more complex refactoring task.

- Prompt 1: Extract a new class named Address

[source,text]
@workspace Using the address related fields from the Person class, create a new Address class. Implement the Address class with a header and cpp file. Follow the pattern of the Person class for generating fields and methods.

- Prompt 2: Update the Person class to use the Address class.

[source,text]
@workspace Replace the address-related fields in the Person class with the Address class. Update the Person class so the Address is created when the Person is create. Also, enable the Address to modified through a Person object.
