name: AsciiDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install AsciiDoc
      run: sudo apt-get install asciidoctor

    - name: Build AsciiDoc site
      run: asciidoctor courseware-adoc -D site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
